#!/bin/sh

# Clears all files generated by HADDOCK in a given directory
# Essentially resets it to right before running haddock for the second time.
# run.cns, ambig.tbl, unambig.tbl, etc are all kept

USAGE="./$( basename $0 ) <rundir>"

if [ $# != "1" ]
then
  echo "Incorrect usage..."
  echo $USAGE
  exit
fi

rundir=$1

if [ ! -d $rundir ]
then
  echo "$rundir not found.."
  exit
fi

cd $rundir

if [ ! -e "run.cns" ]
then
  echo "run.cns not found.. run this script in the root directory of the HADDOCK run"
  exit 1
fi

echo "Cleaning run directory: $rundir"
rm *log *it0* *it1* *out.gz *out *inp *job* cluster* run_*.cns index.html WARNING 2> /dev/null

if [ -d "begin" ]
then
  echo -e "Begin directory: \c"
  cd begin
  rm *psf* *pdb* *list *out file* 2> /dev/null
  cd ../
  if [ -d begin-aa ]
  then
    cd begin-aa
    rm *psf* *pdb* *list *out file* 2> /dev/null
    cd ../
  fi
  echo "Clean!"
fi

if [ -d "structures" ]
then
  echo -e "Structures directory: \c"
  cd structures

  # IT0
  if [ -d "it0" ]
  then
    cd it0
    for f in `ls . | grep -v iteration.cns | grep -v ambig.tbl | grep -v unambig.tbl`
    do
      rm $f 2> /dev/null
    done
    echo -e "it0, \c"
    cd ..
  fi

  # IT1
  if [ -d "it1" ]
  then
    cd it1
    for f in `ls . | grep -v iteration.cns | grep -v ambig.tbl | grep -v unambig.tbl`
    do
      rm $f 2> /dev/null
    done
    if [ -d "analysis" ]
    then
      cd analysis
      for f in `ls . | grep -v iteration.cns`
      do
        rm $f 2> /dev/null
      done
      cd ..
    fi
    echo -e "it1, \c"
  fi

  # Water
  if [ -d "water" ]
  then
    cd water
    for f in `ls . | grep -v iteration.cns | grep -v ambig.tbl | grep -v unambig.tbl`
    do
      rm $f 2> /dev/null
    done
    if [ -d "analysis" ]
    then
      cd analysis
      for f in `ls . | grep -v iteration.cns`
      do
        rm $f 2> /dev/null
      done
      cd ..
    fi
    cd ..
    echo -e "water. Clean!"
  fi
fi

exit
